
// Guide/Controls
i18n.en.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.es.guideControls = '<li><kbd>F11</kbd> / doble clic - Alternar pantalla completa</li><li><kbd>M</kbd> - Configuración</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manual del usuario</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - siguiente canal</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - canal anterior</li><li><kbd>&#8678;</kbd> - abrir lista de canales</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - abrir lista de grupos y otras opciones</li><li><kbd>&#8680;</kbd> - cerrar lista de canales/grupos</li><li><kbd>&#9003;</kbd> - reproducir último canal</li><li><kbd>ESC</kbd> - cerrar la máscara de operación actual</li>';
i18n.it.guideControls = '<li><kbd>F11</kbd> / doppio click - Attiva/disattiva schermo intero</li><li><kbd>M</kbd> - Impostazioni</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manuale utente</li><li><kbd>&#8679;</kbd> / scorrimento del mouse SU - canale successivo</li><li><kbd>&#8681;</kbd> / scorrimento del mouse GIÙ - canale precedente</li><li><kbd>&#8678;</kbd> - apri l\'elenco dei canali</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - apri elenco gruppi e altre opzioni</li><li><kbd>&#8680;</kbd> - chiudi elenco canali/gruppi</li><li><kbd>&#9003;</kbd> - riproduci l\'ultimo canale</li><li><kbd>ESC</kbd> - chiude la maschera operativa corrente</li>';
i18n.fr.guideControls = '<li><kbd>F11</kbd> / double clic - Basculer en plein écran</li><li><kbd>M</kbd> - Paramètres</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manuel de l\'utilisateur</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - chaîne suivante</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - chaîne précédente</li><li><kbd>&#8678;</kbd> - ouvrir la liste des chaînes</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - ouvrir la liste des groupes et autres options</li><li><kbd>&#8680;</kbd> - fermer la liste des canaux/groupes</li><li><kbd>&#9003;</kbd> - lire la dernière chaîne</li><li><kbd>ESC</kbd> - fermer le masque de fonctionnement actuel</li>';
i18n.de.guideControls = '<li><kbd>F11</kbd> / Doppelklick - Vollbild umschalten</li><li><kbd>M</kbd> - Einstellungen</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Benutzerhandbuch</li><li><kbd>&#8679;</kbd> / Maus nach oben scrollen - nächster Kanal</li><li><kbd>&#8681;</kbd> / Maus nach unten scrollen - vorheriger Kanal</li><li><kbd>&#8678;</kbd> - Kanalliste öffnen</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Gruppenliste und andere Optionen öffnen</li><li><kbd>&#8680;</kbd> - Kanal-/Gruppenliste schließen</li><li><kbd>&#9003;</kbd> - Letzten Kanal abspielen</li><li><kbd>ESC</kbd> - Aktuelle Bedienmaske schließen</li>';
i18n.ru.guideControls = '<li><kbd>F11</kbd> / Двойной клик - Включить полноэкранный режим</li><li><kbd>M</kbd> - Настройки</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Руководство пользователя< /li><li><kbd>&#8679;</kbd> / прокрутка мыши ВВЕРХ — следующий канал</li><li><kbd>&#8681;</kbd> / прокрутка мыши ВНИЗ — предыдущий канал</li><li><kbd>&#8678;</kbd> - открыть список каналов</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - открыть список групп и другие параметры</li><li><kbd>&#8680;</kbd> - закрыть список каналов/групп</li><li><kbd>&#9003;</kbd> - воспроизвести последний канал</li><li><kbd>ESC</kbd> - закрыть текущую рабочую маску</li>';
i18n.tr.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.pl.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.pt.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.cs.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.ar.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.fi.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.ro.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.no.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.gr.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';


// CORS
i18n.en.corsHint = '⚠ Manasaananda Trail ⚠' ;
i18n.es.corsHint = '⚠ Es posible que algunos canales no se reproduzcan debido a la estricta política de CORS. <a href="https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Más información y cómo solucionarlo.</a>';
i18n.it.corsHint = '⚠ Alcuni canali potrebbero non essere riprodotti a causa della rigida politica CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Ulteriori informazioni e come risolvere il problema.</a>';
i18n.fr.corsHint = '⚠ Certaines chaînes peuvent ne pas jouer en raison de la politique stricte de CORS. <a href="https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Plus d\'informations et comment résoudre ce problème.</a>';
i18n.de.corsHint = '⚠ Einige Kanäle können aufgrund strenger CORS-Richtlinien möglicherweise nicht abgespielt werden. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Weitere Informationen und wie du dies beheben kannst.</a>';
i18n.ru.corsHint = '⚠ Некоторые каналы могут не воспроизводиться из-за строгой политики CORS. <a href="https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Подробнее о том, как это исправить.</а>';
i18n.tr.corsHint = '⚠ Katı CORS politikası nedeniyle bazı kanallar oynatılamayabilir. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Daha fazla bilgi ve bunun nasıl düzeltileceği</a>.';
i18n.pl.corsHint = '⚠ Niektóre kanały mogą nie być odtwarzane ze względu na surowe zasady CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Więcej informacji i jak to naprawić</a>.';
i18n.pt.corsHint = '⚠ Alguns canais podem não ser reproduzidos devido à política rígida do CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Mais informações e como corrigir isso</a>.';
i18n.cs.corsHint = '⚠ Některé kanály se nemusí přehrávat kvůli přísným zásadám CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Další informace a jak to opravit</a>.';
i18n.ar.corsHint = '⚠ قد لا تعمل بعض القنوات بسبب سياسة CORS الصارمة. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">مزيد من المعلومات وكيفية إصلاح هذا</a>.';
i18n.fi.corsHint = '⚠ Jotkut kanavat eivät välttämättä toistu tiukan CORS-käytännön vuoksi. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Lisätietoja ja kuinka korjata tämä</a>.';
i18n.ro.corsHint = '⚠ Este posibil ca unele canale să nu fie redate din cauza politicii stricte CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Mai multe informații și cum să remediați acest lucru</a>.';
i18n.no.corsHint = '⚠ Noen kanaler kan ikke spille på grunn av strenge CORS-policyer. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Mer informasjon og hvordan du fikser dette</a>.';
i18n.gr.corsHint = '⚠ Ορισμένα κανάλια ενδέχεται να μην παίζουν λόγω αυστηρής πολιτικής CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Περισσότερες πληροφορίες και πώς να το διορθώσετε</a>.';


// First hint in settings
i18n.en.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Insert demo playlist</span><br><br><span class="LINK" onclick="showGuide();">show user guide</span>';
i18n.es.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Insertar lista de reproducción de demostración</span><br><br><span class="LINK" onclick="showGuide();">mostrar la guía del usuario</span>';
i18n.it.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Inserisci playlist demo</span><br><br><span class="LINK" onclick="showGuide();">mostra la guida per l\'utente</span>';
i18n.fr.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Insérer une playlist de démonstration</span><br><br><span class="LINK" onclick="showGuide();">afficher le guide de l\'utilisateur</span>';
i18n.de.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Demo Kanalliste einfügen</span><br><br><span class="LINK" onclick="showGuide();">Bedienungsanleitung anzeigen</span>';
i18n.ru.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Вставить демонстрационный плейлист</span><br><br><span class="LINK" onclick="showGuide();">показать руководство пользователя</span>';
i18n.tr.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Demo çalma listesi ekle</span><br><br><span class="LINK" onclick="showGuide();">kullanım kılavuzunu göster</span>';
i18n.pl.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Wstaw playlistę demonstracyjną</span><br><br><span class="LINK" onclick="showGuide();">pokaż instrukcję obsługi</span>';
i18n.pt.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Inserir playlist demo</span><br><br><span class="LINK" onclick="showGuide();">mostrar guia do usuário</span>';
i18n.cs.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Vložte demo playlist</span><br><br><span class="LINK" onclick="showGuide();">zobrazit uživatelskou příručku</span>';
i18n.ar.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">أدخل قائمة التشغيل التجريبية</span><br><br><span class="LINK" onclick="showGuide();">عرض دليل المستخدم</span>';
i18n.fi.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Lisää demosoittolista</span><br><br><span class="LINK" onclick="showGuide();">näytä käyttöohje</span>';
i18n.ro.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Inserați lista de redare demonstrativă</span><br><br><span class="LINK" onclick="showGuide();">arata ghidul utilizatorului</span>';
i18n.no.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Sett inn demospilleliste</span><br><br><span class="LINK" onclick="showGuide();">vis brukerveiledning</span>';
i18n.gr.helpHint = '<span class="LINK" onclick="oInputM3u.scrollIntoView(); oInputM3u.value = \'https://iptvacc.000webhostapp.com/p2.php\'; downloadButton();">Εισαγωγή λίστας αναπαραγωγής επίδειξης</span><br><br><span class="LINK" onclick="showGuide();">εμφάνιση οδηγού χρήστη</span>';


// Donate without QR-codes for browser/mobile
i18n.en.donate = 'If you like, you can leave a donation:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.es.donate = 'Si gustas, puedes dejar una donación:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.it.donate = 'Se vuoi, puoi lasciare una donazione:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.fr.donate = 'Si vous le souhaitez, vous pouvez faire un don:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.de.donate = 'Wenn du möchtest, kannst du etwas spenden:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.ru.donate = 'Если хотите, можете оставить пожертвование:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.tr.donate = 'Dilerseniz bağış bırakabilirsiniz:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.pl.donate = 'Jeśli chcesz, możesz zostawić darowiznę:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.pt.donate = 'Se quiser, pode deixar uma doação:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.cs.donate = 'Pokud chcete, můžete zanechat dar:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.ar.donate = 'إذا أردت ، يمكنك ترك تبرع: <br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.fi.donate = 'Halutessasi voit jättää lahjoituksen:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.ro.donate = 'Dacă doriți, puteți lăsa o donație:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.no.donate = 'Hvis du vil, kan du legge igjen en donasjon:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
i18n.gr.donate = 'Αν θέλετε, μπορείτε να αφήσετε μια δωρεά:<br><a href="http://iptvacc.rf.gd/?donate=1" target="_blank">http://iptvacc.rf.gd</a>';
